### ISSUE TITLE
Non-equidistance intervals

### ISSUE THREAD

**Issue by frbl** [roqua/physiqual#16]
Currently physiqual only offers support for protocols where the measurements are a given distance apart. We could also introduce either:
- Random measurement moments, where the scheduling moments are given using a json file (for example)
- Non equidistance measurement points, that is, one at 10, one at 11, one at 5 and one at 12 (every day the same)

**Comment by emerencia** [comment]
You can't use non-equidistant measurement points in any time series analysis of the data (and I don't think there's many other analyses that can be done with repeated measurements). So necessarily, when you measure at random intervals, or at distinct intervals during the day, there will be a later step in the process where you resample those values to equidistant intervals. If people use Physiqual to add physical data to their existing measurement points, they might as well skip the step where they match the data up with possibly random intervals and ask of physiqual directly the equidistant intervals. Doing it the other way (asking physical to return the data in nonequidistant time intervals and then resampling those to equidistant time intervals) leads to a loss in precision.

**Comment by frbl** [comment]
Well, they do not need to use a time series analysis technique. What about 3mpca or multilevel modelling? I think both work with non-equidistant measurement points. Physiqual focuses on ESM/EMA data, not on time-series analysis I guess.

**Comment by emerencia** [comment]
If those techniques don't go through the same resampling process then sure. I would say add it if it's not too much work.

**Comment by frbl** [comment]
Although we are able to generate a schedule which is not equidistant, it is not possible to use these buckets in the current clustering method. This method should be improved so it only depends on the data provided to it, instead of assuming equidistance.

**Comment by emerencia** [comment]
The consensus we reached was to not support the non-equidistance intervals for now.

Do we want to remove/comment out the DailyBucketGenerator class or just leave it there unused?

**Comment by frbl** [comment]
Let's remove it.

**Comment by emerencia** [comment]
Agreed.

**Comment by frbl** [comment]
fixed in #71
