### ISSUE TITLE
Correct combination of the two dataservices

### ISSUE THREAD

**Issue by frbl** [roqua/physiqual#40]
Er zijn verschillende use-cases die we moeten afhandelen:

- Een sensor geeft 0, de ander geeft waarden (selecteer de hoogste)
- Beide sensoren geven data (niet 0) (selecteer het gemiddelde)
 - Wat als er heel veel verschil tussen de uitgelezen waarden zit (i.e., 1 sensor heb je om, is min of meer normaal, en de ander geeft vaak 0, maar soms 3 a 4 (je hebt hem niet om maar hij viel van de tafel).

**Comment by emerencia** [comment]
Ik zou altijd de hoogste kiezen. Precies om de reden zie je zelf ook al aangeeft. Als je in 6 uur, 1 uur, of in 1 minuut, meer stappen registreert met stappenteller A dan met stappenteller B, dan kan het altijd zo zijn dat je stappenteller B een deel van de tijd niet om had.

Hoe is het nu geïmplementeerd?

**Comment by emerencia** [comment]
The decision here is to let each user choose between Fitbit or Google fit, and only allow them to add information for one, i.e., to have one physiqual_token. We never merge Google Fit data with Fitbit data.

There should be a way to retrieve which type of

**Comment by emerencia** [comment]
Duplicate of #69.
