### ISSUE TITLE
Make physiqual similar to Elske's manual analysis

### ISSUE THREAD

**Issue by frbl** [roqua/physiqual#61]
Currently there is a small difference between elske's export and ours.

**Comment by frbl** [comment]
Document why this is the case

**Comment by emerencia** [comment]
There no longer is an error by setting 10:31 as starting time. We could make a note of this in the Physiqual paper @frbl.

**Comment by frbl** [comment]
Added a line to the paper,still needs several revisions but at least we won't forget it.
